variables:
- group: common
- template: /.azuredevops/variables-global.yml

resources:
  repositories:
  - repository: aomp_repo
    type: github
    endpoint: ROCm
    name: ROCm/aomp
    ref: amd-mainline-open
  - repository: aomp-extras_repo
    type: github
    endpoint: ROCm
    name: ROCm/aomp-extras
    ref: amd-mainline-open
  - repository: flang_repo
    type: github
    endpoint: ROCm
    name: ROCm/flang
    ref: amd-mainline-open
  - repository: llvm-project_repo
    type: github
    endpoint: ROCm
    name: ROCm/llvm-project
    ref: amd-mainline-open
  pipelines:
  - pipeline: rocr-runtime_pipeline
    source: \ROCR-Runtime
    trigger:
      branches:
        include:
        - amd-master
# this job will only be triggered after successful build sequence of llvm-project and ROCR-Runtime

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/aomp.yml
    parameters:
      checkoutRepo: aomp_repo
